[tool.pytest.ini_options]
addopts = "--capture=tee-sys --ignore-glob=common/tests/* --ignore-glob=tests/test_visuals/*"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
[tool.black]
line-length = 85
exclude = '''   
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | .pytest_cache
    | buck-out
  )/
)
'''
[tool.coverage]
run.omit = [
  "tr_app/*",
  "static/*",
  "templates/*",
  "requirements/*",
  "tests/*",
  "common/*",
  "celery_starter.py",
  "PaddleOCR/*"
]
  
